"""One-off asset-generation script (Session 8 후속 9): builds
assets/soda_can/can_side.obj, a plain parametric cylinder-side mesh with explicit
per-vertex UV coordinates (a wraparound `u` from 0 to 1, `v` from bottom to top).

Why this exists: the vendored soda_can.stl (models/full_scene.xml's earlier visual mesh)
has no UV data -- STL never carries texture coordinates -- so the can's label texture
(assets/soda_can/soda_can_label.png) can't be applied to it. Tried relying on MuJoCo's
automatic texture coordinate generation for a `type="cylinder"` primitive geom instead
(no mesh needed) and found empirically it does not produce a clean single circumferential
wrap for a photographic/detailed 2D texture -- confirmed directly (dumped MuJoCo's own
loaded texture data to rule out a load/decode bug; the pixels were correct) that only an
explicit-UV mesh (OBJ, which does support `vt` lines, unlike STL) renders the label
legibly. Regenerate this file (rather than hand-editing the OBJ) if the can's
radius/height ever changes.

Run: python3 tests/generate_can_label_mesh.py
"""

import math
import pathlib

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "assets" / "soda_can" / "can_side.obj"

# Matches can_geom's validated collision cylinder (r=0.033, half-height=0.055) minus the
# two 0.0025-thick cap discs modeled as separate plain-material geoms in full_scene.xml,
# so the labeled side + caps butt together with no gap/overlap: 0.050 + 0.0025*2 = 0.055.
RADIUS = 0.033
HALF_HEIGHT = 0.050
N_SEGMENTS = 64


def main():
    verts = []
    uvs = []
    # N+1 columns, not N: the last column spatially duplicates the first (same x,y) but
    # gets u=1.0 instead of u=0.0 -- without this the texture's right edge would wrap
    # back and blend into its own left edge across the seam instead of finishing cleanly.
    for col in range(N_SEGMENTS + 1):
        theta = 2 * math.pi * (col / N_SEGMENTS)
        x, y = RADIUS * math.cos(theta), RADIUS * math.sin(theta)
        u = col / N_SEGMENTS
        verts.append((x, y, -HALF_HEIGHT))
        uvs.append((u, 0.0))
        verts.append((x, y, HALF_HEIGHT))
        uvs.append((u, 1.0))

    lines = ["# generated by tests/generate_can_label_mesh.py -- do not hand-edit\n"]
    for x, y, z in verts:
        lines.append(f"v {x:.6f} {y:.6f} {z:.6f}\n")
    for u, v in uvs:
        lines.append(f"vt {u:.6f} {v:.6f}\n")

    for col in range(N_SEGMENTS):
        b0, t0 = 2 * col + 1, 2 * col + 2  # OBJ indices are 1-based
        b1, t1 = 2 * (col + 1) + 1, 2 * (col + 1) + 2
        lines.append(f"f {b0}/{b0} {b1}/{b1} {t0}/{t0}\n")
        lines.append(f"f {t0}/{t0} {b1}/{b1} {t1}/{t1}\n")

    OUT_PATH.write_text("".join(lines))
    print(f"wrote {OUT_PATH} -- {len(verts)} verts, {N_SEGMENTS * 2} faces")


if __name__ == "__main__":
    main()
