"""One-off asset-generation script (Session 8 후속 9, rewritten 후속 10): builds
assets/soda_can/can_side_detail.obj and can_cap_detail.obj, both derived directly from the
vendored assets/soda_can/soda_can.stl (the ROBOTIS-adjacent detailed can mesh -- rim, pull
tab, slightly domed top, concave base -- vs a bare cylinder), each with explicit per-vertex
UV coordinates so the label texture (assets/soda_can/soda_can_label.png) can actually be
applied to it. STL never carries UV data, so this script re-derives it geometrically rather
than hand-authoring it.

Why two separate meshes instead of one: profiling the STL's own vertex radius as a function
of height (see NOTES.md "Phase 5 후속 10") showed the mesh is a near-perfect constant-radius
cylinder from about z_frac=0.03 to 0.94 of its own height range, with almost all of its
~15k vertices concentrated in the complex top ~5% (dome/rim/tab) and bottom ~3% (concave
base) -- i.e. the geometry itself already tells you where the "label goes here" band is,
independent of face-normal heuristics (which turned out unreliable: ~78% of faces have a
mostly-vertical normal at even a loose threshold, because the tab/rim detail is locally
steep despite being part of what's visually "the cap", not "the side"). Side faces get a
real cylindrical UV wrap (u = angle/2pi around the axis, v = height fraction); cap faces
(everything outside the band) get a trivial UV since they use a flat, untextured material.

UV computed per-face-corner (not shared per-vertex) for the side mesh, each face
individually "unwrapping" its 3 corner angles (adding/subtracting 2*pi as needed so they're
within pi of each other) before converting to u -- necessary because this is an arbitrary,
irregular triangulation (not a hand-built regular grid), so there's no fixed known set of
"seam" vertices to duplicate ahead of time the way the first (bare-cylinder) attempt at this
did; doing it per-face instead handles every triangle correctly regardless of whether it
happens to straddle the angle=+-pi seam.

Run: python3 tests/generate_can_label_mesh.py
"""

import pathlib

import numpy as np
import trimesh

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
STL_PATH = REPO_ROOT / "assets" / "soda_can" / "soda_can.stl"
SIDE_OUT = REPO_ROOT / "assets" / "soda_can" / "can_side_detail.obj"
CAP_OUT = REPO_ROOT / "assets" / "soda_can" / "can_cap_detail.obj"

# Fraction of the mesh's own native z-range (see module docstring's profiling result:
# constant radius holds from ~0.03 to ~0.94) -- kept a bit inside that measured band for
# margin so no partially-curved transition face gets misclassified as "side".
SIDE_Z_FRAC_LO = 0.05
SIDE_Z_FRAC_HI = 0.92


def write_obj(path, verts, faces, uvs_per_face_corner=None):
    lines = [f"# generated by tests/generate_can_label_mesh.py -- do not hand-edit\n"]
    for v in verts:
        lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
    if uvs_per_face_corner is not None:
        vt_idx = 1
        for face_uvs in uvs_per_face_corner:
            for u, v in face_uvs:
                lines.append(f"vt {u:.6f} {v:.6f}\n")
        for fi, face in enumerate(faces):
            a, b, c = face + 1  # OBJ is 1-indexed
            base = fi * 3
            lines.append(f"f {a}/{base+1} {b}/{base+2} {c}/{base+3}\n")
    else:
        for face in faces:
            a, b, c = face + 1
            lines.append(f"f {a} {b} {c}\n")
    path.write_text("".join(lines))


def main():
    mesh = trimesh.load(STL_PATH)
    verts = mesh.vertices
    faces = mesh.faces
    z = verts[:, 2]
    z_lo_all, z_hi_all = z.min(), z.max()
    z_lo = z_lo_all + SIDE_Z_FRAC_LO * (z_hi_all - z_lo_all)
    z_hi = z_lo_all + SIDE_Z_FRAC_HI * (z_hi_all - z_lo_all)

    face_z = z[faces].mean(axis=1)
    is_side = (face_z >= z_lo) & (face_z <= z_hi)
    side_faces = faces[is_side]
    cap_faces = faces[~is_side]
    print(f"side faces: {len(side_faces)}  cap faces: {len(cap_faces)}  "
          f"(of {len(faces)} total)")

    # Side mesh: per-face-corner cylindrical UV, each face's angles unwrapped independently.
    side_uvs = []
    for face in side_faces:
        pts = verts[face]
        angles = np.arctan2(pts[:, 1], pts[:, 0])
        for i in (1, 2):
            diff = angles[i] - angles[0]
            if diff > np.pi:
                angles[i] -= 2 * np.pi
            elif diff < -np.pi:
                angles[i] += 2 * np.pi
        us = angles / (2 * np.pi) + 0.5
        vs = np.clip((pts[:, 2] - z_lo) / (z_hi - z_lo), 0.0, 1.0)
        side_uvs.append(list(zip(us, vs)))
    write_obj(SIDE_OUT, verts, side_faces, side_uvs)
    print(f"wrote {SIDE_OUT}")

    # Cap mesh: geometry only, no texture (flat material), so UV is irrelevant -- but MuJoCo
    # requires an OBJ referenced by a textured... no, this mesh isn't textured, so a plain
    # position-only OBJ (no vt/f-with-slash) is fine and simpler.
    write_obj(CAP_OUT, verts, cap_faces, uvs_per_face_corner=None)
    print(f"wrote {CAP_OUT}")


if __name__ == "__main__":
    main()
